In [1]:
import numpy as np

In [12]:
a=np.arange(1,5)

In [13]:
b=a.reshape(2,2)

In [14]:
np.linalg.det(b)

-2.0000000000000004

In [15]:
a

array([1, 2, 3, 4])

In [16]:
b

array([[1, 2],
       [3, 4]])

In [17]:
c=-2*b
c

array([[-2, -4],
       [-6, -8]])

In [18]:
np.linalg.det(c)

-8.000000000000002

In [20]:
import random

In [23]:
d=np.random.rand(2,2)

In [24]:
d

array([[0.97111657, 0.94800031],
       [0.54327883, 0.80275836]])

In [26]:
np.linalg.det(d)

0.26454344661498735

In [27]:
e=-2*d

In [28]:
e

array([[-1.94223313, -1.89600062],
       [-1.08655766, -1.60551672]])

In [29]:
np.linalg.det(e)

1.0581737864599494

In [31]:
while True:
    A=np.random.randint(-1,1,size=(5,5))
    deter_A=np.linalg.det(A)
    if deter_A==-1:
        break
print(A)       

[[-1  0 -1 -1 -1]
 [ 0  0 -1  0 -1]
 [-1  0  0 -1 -1]
 [ 0 -1 -1  0 -1]
 [-1  0  0  0  0]]


In [33]:
np.linalg.det(-3*A)

243.00000000000017