In [1]:
import numpy as np

In [3]:
u=np.array([[1,1,0], [0,1,1], [1,2,3]])

In [5]:
u=u.T

In [6]:
u

array([[1, 0, 1],
       [1, 1, 2],
       [0, 1, 3]])

In [7]:
u_1=np.linalg.inv(u)

In [8]:
u_1

array([[ 0.5,  0.5, -0.5],
       [-1.5,  1.5, -0.5],
       [ 0.5, -0.5,  0.5]])

In [9]:
len(u)

3

In [37]:
a=np.random.rand(3,3)

In [31]:
d=np.array([[-1,0,0],[0,2,0],[0,0,2]])

In [38]:
a

array([[0.06968088, 0.22979623, 0.8880808 ],
       [0.38149147, 0.63568562, 0.16329725],
       [0.85909583, 0.11908871, 0.07512225]])

In [50]:
while True:
    a=np.random.randint(-1,1,size=(3,3))
    right=np.dot(np.dot(u,d),u_1)
    if a.all()==right.all():
        print(a)
        break

[[-1  0  0]
 [-1 -1 -1]
 [-1  0  0]]


In [57]:
np.linalg.eig(ddd)

(array([ 2., -1.,  2.]),
 array([[ 0.70710678,  0.70710678,  0.64522571],
        [-0.70710678,  0.70710678,  0.11070323],
        [ 0.        ,  0.        ,  0.75592895]]))

In [55]:
ddd=np.dot(np.dot(u,d),u_1)