## Tapşırıq 1

(5,5) ölçülü müsbət tam ədədlərdən ibarət array-in polindrom olan sətir və ya sütunlarını göstərin. Polindrom ədəd dedikdə məsələn: 323, 6336, 54245, 623326 nəzərdə tutulur.

In [5]:
# your code

import numpy as np
array = np.array([[1,0,7,0,1],
                [2,120,4,1,10],
                [1,3,0,3,1],
                [1,120,31,1,19],
                [11,0,7,0,11]])
for x in array:
    if list(x)==list(x)[::-1]:
        print(x)
y=array.T
for a in y:
    if list(a)==list(a)[::-1]:
        print(a)

[1 0 7 0 1]
[1 3 0 3 1]
[11  0  7  0 11]
[  0 120   3 120   0]
[0 1 3 1 0]


## Tapşırıq 2

İstənilən 2-ölçülü array-in hər sətiri üçün ən böyük ədədlə ən kiçik ədədin nisbətini tapın

In [6]:
# your code
array2 = np.array([[1,5,7,3,1],
                [2,120,4,1,10],
                [1,3,4,3,1],
                [1,120,31,1,19],
                [11,8,7,9,11]])
for a in array2:
    print(max(a)/min(a))

7.0
120.0
4.0
120.0
1.5714285714285714


## Tapşırıq 3

Verilmiş 2-ölçülü array-in hər elementinin əvəzinə onun rankını yazaraq yeni bir array yaradın

Gözlənilən cavab:

[[4 2 6 0 8]

[7 9 3 5 1]]

In [7]:
# your code
import numpy as np
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
b=a.copy()
c=b.ravel()
d=np.sort(c)
arr01=np.array([],dtype='int64')
for i in c:
    ff=np.where(i==d)[0][0]
    arr01=np.append(arr01,ff)
list0=[]
for x in arr01:
    list0.append(x)
list1=list0[::-1]
for h in list1:
    if list1.count(h)>1:
        ind=list1.index(h)
        list1[ind]=h+1
list2=list1[::-1]
arr02=np.array(list2)
arr02=np.reshape(arr02,(2,5))
print(arr02)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


## Tapşırıq 4

Verilən bir ölçülü array-dən one hot encoding prinsipi ilə yeni bir array yaradın  

In [72]:
# your code
arr = np.array([2, 3, 2, 2, 2, 1])
# arr1=np.unique(arr)
# arr2=np.array([],dtype='int64')
# for i in arr:
#     if i==arr1[0]:
#         arr2=np.append(arr2,[1, 0, 0])
#     elif i==arr1[1]:
#         arr2=np.append(arr2,[0, 1, 0])
#     elif i==arr1[2]:
#         arr2=np.append(arr2,[0, 0, 1])
# arr2=np.reshape(arr2,(6,3))
# arr1=np.reshape(arr1,(1,3))
# arr3=np.r_[arr1,arr2]
# arr4=np.insert(arr,0,-999)
# arr4=np.reshape(arr4,(7,1))
# arr5=np.c_[arr4,arr3]
# print(arr5)
rs=len(arr)
cs=len(np.unique(arr))
arr1=np.full((rs,cs),0)
for ind, elm in enumerate(arr):
    position = np.where(np.unique(arr) == elm)
    arr1[ind,position] = 1  
arr2=np.c_[arr,arr1]
arr3=np.insert(np.unique(arr),0,-999)
arr3=np.reshape(arr3, (1,len(arr3)))
arr4=np.r_[arr3,arr2]
print(arr4)

[[-999    1    2    3]
 [   2    0    1    0]
 [   3    0    0    1]
 [   2    0    1    0]
 [   2    0    1    0]
 [   2    0    1    0]
 [   1    1    0    0]]


## Tapşırıq 5

Verilmiş array-in top 5 elementini və onların pozisiyalarını əldə edin

In [20]:
import numpy as np
np.random.seed(100)
a = np.random.randint(1,50, 20).reshape(4,5)
print(a)
# b=np.apply_along_axis(max,axis=1,arr=a)
# c=np.apply_along_axis(max,axis=0,arr=a)
# d=np.r_[b,c]
# dlist=[]
# for b in d:
#     if b not in dlist:
#         dlist.append(b)
# dlist.sort()
# print('\n',dlist)
# print('')
# for i in a:
#     for x in i:
#         if x in dlist:
#             print(np.where(a==x))     

b=a.copy()
c=b.ravel()
list0=[]
list1=[]
for i in c:
    list1.append(i)
list1=list(set(list1))
for x in range(0,5):
    for i in list1:
        if i==max(list1):
            list0.append(i)
            list1.remove(i)
list0.remove(min(list0))
list0.sort()
for elm in list0:
    print(f'Element: {elm} On position: {np.where(c==elm)[0]}')

[[ 9 25  4 40 24]
 [16 49 11 31 35]
 [ 3 35 15 35 49]
 [25 16 37 44 17]]
Element: 35 On position: [ 9 11 13]
Element: 37 On position: [17]
Element: 40 On position: [3]
Element: 44 On position: [18]
Element: 49 On position: [ 6 14]
