## Exercise 1

İstənilən ölçüdə array yaradın. Array-in ətrafındakı elementləri 1-lərdən, daxilindəkilər isə 0-lardan ibarət olmalıdır.

Məsələn:

1)

    [[1,1,1,1,1],
     [1,0,0,0,1],
     [1,0,0,0,1],
     [1,1,1,1,1]]
     
2)

    [[1,1,1],
     [1,0,1],
     [1,1,1]]
     
3)

    [[1,1,1,1],
     [1,0,0,1],
     [1,1,1,1]]     

In [2]:
# your code
import numpy as np
arr0=np.array([[4,8,9],[74, 25, 4], [3, 284, 39],[75, 22, 0],[5, 254, 29]])
print(arr0)
arr1=arr0.copy()
def birle(arrayimiz):
    arrayimiz=np.full(arrayimiz.shape[0], 1)
    return arrayimiz
arr1=np.apply_along_axis(birle,axis=0,arr=arr0)
for i in range(0,arr0.shape[0]):
    if i==0 or i==arr0.shape[0]-1:
        continue
    else:
        arr1[i][1:len(arr1[i])-1]=0
print(f'\n{arr1}') 

[[  4   8   9]
 [ 74  25   4]
 [  3 284  39]
 [ 75  22   0]
 [  5 254  29]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]

[[1 1 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [1 1 1]]


## Exercise 2
Verilmiş 1 ölçülü massivin [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14] hər 3-cü elementi ilə başlayan 6 sətir və 4 sütundan ibarət yeni massiv yaradın

In [35]:
# your code
arr0=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
list1=[]
for i in arr0[::2]:
    list1.append(arr0[arr0==i][0])
list1.remove(14)
arr1=np.array([[]],dtype='int64')
for i in list1:
    arr1=np.append(arr1,arr0[i:i+4])
arr1=arr1[:-3]
arr1=arr1.reshape((6,4))
print(arr1)

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


## Exercise 3
Random ədədlərdən ibarət 2 ölçülü massiv yaradın. Yaratdığınız massivin hər sətrini tərsinə çevirməklə yeni massiv yaradın.

Məsələn:
 
     [[1,2,3,4,5],
      [6,7,8,9,10],
      [10,11,12,13,14]]
 
Gözlənilən cavab:
 
     [[5,4,3,2,1],
      [10,9,8,7,6],
      [14,13,12,11,10]]

In [5]:
# your code
arr0=np.array([[4,8,9,55],[74, 25, 4,12], [3, 284, 39,48]])
print(f'{arr0}\n')
for i in arr0:
    arr0[arr0==i]=arr0[arr0==i][::-1]
print(arr0)

[[  4   8   9  55]
 [ 74  25   4  12]
 [  3 284  39  48]]

[[ 55   9   8   4]
 [ 12   4  25  74]
 [ 48  39 284   3]]


## Exercise 4
Random ədədlərdən ibarət 2 ölçülü massiv yaradın. Yaratdığınız massivin sətirləri ilə sütunlarının yerini dəyişməklə yeni massiv yaradın.

Məsələn:

    [[1,2,3,4,5],
     [6,7,8,9,10],
     [10,11,12,13,14]]

Gözlənilən cavab:

    [[1,6,10],
     [2,7,11],
     [3,8,12],
     [4,9,13],
     [5,10,14]]


​

In [4]:
# your code
np.random.seed(662)
arr0= np.random.randint(100,size=(3,5))
print(arr0)
arr1=arr0.T
print(f'\n{arr1}')

[[63 74  6 52 87]
 [10 20 76  7 69]
 [85 37 70 38 79]]

[[63 10 85]
 [74 20 37]
 [ 6 76 70]
 [52  7 38]
 [87 69 79]]


## Exercise 5

Verilmiş 2 ölçülü massivdən diagonalı bu massivin sətirlərindən ibarət olan yeni massiv yaradın.

Gözlənilən cavab:

       [[[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]],

       [[4, 0, 0],
        [0, 5, 0],
        [0, 0, 6]],

       [[7, 0, 0],
        [0, 8, 0],
        [0, 0, 9]]]

In [3]:
# your code
import numpy as np
np.random.seed(10)
arr = np.random.randint(100,size=(3,3))
print(f'{arr}\n')
for i in range(0,arr.shape[0]):
    print(np.diag(v=arr[i]))

[[ 9 15 64]
 [28 89 93]
 [29  8 73]]

[[ 9  0  0]
 [ 0 15  0]
 [ 0  0 64]]
[[28  0  0]
 [ 0 89  0]
 [ 0  0 93]]
[[29  0  0]
 [ 0  8  0]
 [ 0  0 73]]
